
CREATE TABLE IF NOT EXISTS public.junta_directiva (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cargo text not null,
  imagen_url text,
  orden integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

