ALTER TABLE eventos ADD COLUMN IF NOT EXISTS ubicacion TEXT NULL;
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS link_detalles TEXT NULL;
ALTER TABLE eventos ADD COLUMN IF NOT EXISTS link_mapa TEXT NULL;
